- src/pages/MainPage/MainPage.jsx
- src/pages/MainPage/style.js
> [feat] 메인페이지 UI 1.0v 완성

- src/pages/LandingPage/LandingCss.js
- src/pages/LandingPage/LandingPage.jsx
- src/shared/Router.js
> LandingPageUi 1.0v 완성

- src/pages/LoginPage/LoginPage.jsx
- src/pages/SingUpPage/SignUpPage.jsx
- src/pages/SingUpPage/style.js
- src/shared/Router.js
> [feat] 회원가입 페이지 1차 UI

- package-lock.json
- package.json
- src/components/AllBankList/AllBankList.jsx
- src/components/AllBankList/style.js
- src/pages/BankList.jsx
- src/pages/ServicePage/ServicePage.jsx
- src/pages/ServicePage/ServicePageCss.js
최고금리 순으로 가져오는데 12개월 기준으로 가져왔습니다.(12개월은 각각 상품들이 다 가지고 있는 것같아서 누락이 가장 적을듯합니다.)
> feat.최고금리 순으로 가져오기

- src/App.jsx
- src/pages/ServicePage/ServicePage.jsx
- src/pages/ServicePage/style.js
전체적인 UI 수정, 탭 버튼, 예금,적금 버튼 기능 구현.
> fix. ServicePageUi수정 및 기능 추가.

- package-lock.json
- package.json
- src/components/AllBankList/SavingAllBankList.jsx
- src/components/AllBankList/style.js
- src/components/SearchBankList/SearchBankList.jsx
- src/components/SearchBankList/SearchInput.jsx
- src/components/SearchBankList/style.js
- src/pages/ServicePage/ServicePage.jsx
- src/pages/ServicePage/style.js
1. 리스트 ui
2. 검색리스트 ui
3. 푸터와 겹치는 ui 제거 
4. 검색기능에 은행상품명 추가
5. 적금 예금 선택기능 추가
**react-icons 설치(npm install react-icons)
> fix. servicePage UI , 기능구현 fix

- src/components/AllBankList/AllBankList.jsx
- src/components/AllBankList/SavingAllBankList.jsx
- src/components/DetailProduct/DepositDetail.jsx
- src/components/DetailProduct/SavingDetail.jsx
- src/components/DetailProduct/style.js
- src/components/ServicePage/AllBank.jsx
- src/config/firebase.js
- src/pages/ServicePage/ServicePage.jsx
- src/pages/ServicePage/style.js
1. 리스트 나열 기능 수정
2. 더보기 클릭 기능 수정과 상세보기 토글 css작업 수정
3. 예금정보 baseLists는 기존에 있던 상우님 함수로 실행 -> 잘나오는것도 확인
4. 검색 시 나오는 상세보기토글은 아직 진행 중
> fix. 리스트기능수정(중간 병합)

- src/components/AllBankList/AllBankList.jsx
- src/components/AllBankList/SavingAllBankList.jsx
- src/components/DetailProduct/DepositDetail.jsx
- src/components/DetailProduct/SavingDetail.jsx
- src/components/DetailProduct/style.js
- src/components/SearchBankList/Detail/SearchDepositDetail.jsx
- src/components/SearchBankList/Detail/SearchSavingDetail.jsx
- src/components/SearchBankList/SearchBankList.jsx
- src/components/SearchBankList/SearchComponent/SearchDepositLists.jsx
- src/components/SearchBankList/SearchComponent/SearchSavingLists.jsx
- src/components/SearchBankList/SearchInput.jsx
- src/components/ServicePage/AllBank.jsx
- src/pages/ServicePage/ServicePage.jsx
- src/routes/index.js
1.상품 마다 상세보기 내용 정리
( 최소 개월 수 , 최저한도 값 표현 정리)
2.리스트마다 놓친 css 기능 수정
3. 선택 시 스테이징 가능 확인 (우선적으로 예금 상품만 확인)
> fix. 상품검색탭 전체 기능 수정

- src/components/AllBankList/AllBankList.jsx
- src/components/SearchBankList/SearchComponent/SearchDepositLists.jsx
- src/pages/MyPage/MyPage.jsx
- src/routes/index.js
> fix. 중간 코드 병합

- src/components/GlobalComponents/Header/style.js
- src/pages/MainPage/MainPage.jsx
- src/pages/MainPage/style.js
> feat.로그인시 이름 변경 및 헤더UI 수정

- src/components/CalculatorList/CalculatorList.jsx
- src/components/Mypage/BookmarkPrdtItem.jsx
- src/config/firebase.js
- src/pages/ServicePage/ServicePage.jsx
계산기(예금)부분에서 개월 수에 따라서 리스트 나오게하는 부분 수정 했습니다.( +자세히)
> feat. 계산기list실행 추가기능

- src/components/AllBankList/AllBankList.jsx
- src/components/AllBankList/SavingAllBankList.jsx
- src/components/BookMarkList/DetailBookMark.jsx
- src/components/Bookmarks.jsx
- src/components/DetailProduct/DepositDetail.jsx
- src/components/DetailProduct/style.js
- src/components/Mypage/BookmarkPrdtItem.jsx
- src/components/Mypage/BookmarkPrdtList.jsx
- src/components/SearchBankList/Detail/SearchDepositDetail.jsx
- src/components/SearchBankList/SearchComponent/SearchDepositLists.jsx
- src/components/SearchBankList/SearchComponent/SearchSavingLists.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/MyPage/style.js
> feat. 마이페이지 찜목록 리스트 가져오기

- src/components/AllBankList/AllBankList.jsx
- src/components/AllBankList/SavingAllBankList.jsx
- src/components/BookMarkList/DetailBookMark.jsx
- src/components/CalculatorList/CalculatorList.jsx
- src/components/Mypage/BookmarkPrdtItem.jsx
- src/components/Product/Product.jsx
- src/components/Product/SavingProduct.jsx
- src/components/SearchBankList/SearchComponent/SearchDepositLists.jsx
- src/components/SearchBankList/SearchComponent/SearchSavingLists.jsx
- src/components/ServicePage/Bookmarks.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/ServicePage/ServicePage.jsx
- src/pages/SignUpPage/SignUpPage.jsx
> feat. 찜한목록 불러오기 중간 저장

- .env
- src/components/AllBankList/AllBankList.jsx
- src/components/AllBankList/SavingAllBankList.jsx
- src/components/CalculatorList/CalculatorList.jsx
- src/components/DetailProduct/SavingDetail.jsx
- src/pages/ServicePage/ServicePage.jsx
1.상품계산 시 적금 리스트 나오는 부분 수정
2.적금 상품 상세설명 부분 수정
3.스테이징 시 해당 상품 로고 수정
> fix. 서비스페이지 적금 리스트 기능 수정

- src/components/ServicePage/Bookmarks.jsx
productType(예금적금 구분)으로 필터링하다가 모달 측 북마크에서 이상생겨서 다시 빼고 저장
> fix. productTypes에러

- src/components/Community/LoggedIn.jsx
- src/components/Community/style.js
- src/components/MainPage/Tipper.jsx
- src/components/PostingModal/PostingModal.jsx
- src/components/PostingModal/style.js
- src/pages/Community/CommunityPage.jsx
새로고침시 데이터 불러오기, 카테고리별로 데이터 불러오기
> feat.게시글 카테고리별 불러오기 구현

- src/components/Community/Like.jsx
- src/components/MainPage/BestTipper.jsx
- src/components/MainPage/BestTipperList.jsx
- src/components/Mypage/UserAccount/ChangePassword.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/MyPage/style.js
> feat. 대쉬보드 수정

- .env
- src/components/GlobalComponents/Header/Header.jsx
- src/components/MainPage/Tipper.jsx
- src/data/InsertData.jsx
> fix. 배포 전 점검

- src/components/Community/Like.jsx
- src/components/MainPage/BestProducts.jsx
- src/components/MainPage/BestTipperList.jsx
- src/components/Mypage/UserAccount/ChangeNickname.jsx
- src/components/Mypage/UserAccount/ChangePassword.jsx
- src/components/SearchBankList/style.js
- src/pages/MainPage/style.js
- src/pages/MyPage/style.js
1. mypageInput 크기 조절
2. 홈화면에 랭킹 은행 로고 조절
3. 서비스페이지 리스트 width 조절
> fix. mypageInput 크기 조절

- src/components/SecondSectionAnimation/AnimationFirst.jsx
- src/components/SecondSectionAnimation/AnimationSecond.jsx
- src/components/SecondSectionAnimation/AnimationThird.jsx
- src/pages/ServicePage/ServicePage.jsx
- src/pages/ServicePage/style.js
> fix. 서비스 수정 및 기능추가

- .gitignore
- src/components/MainPage/BestProducts.jsx
- src/components/Product/Product.jsx
- src/components/ServicePage/Bookmarks.jsx
- src/pages/Admin/Admin.jsx
- src/pages/Error/NotFoundPage.jsx
- src/routes/index.js
> Feature/edit bookmark 1.8v

- src/components/Community/Like.jsx
- src/components/Community/style.js
- src/components/GlobalComponents/Footer/style.js
- src/components/MainPage/BestProducts.jsx
- src/components/MainPage/BestTipperList.jsx
- src/components/Mypage/UserAccount/ChangeNickname.jsx
- src/components/Mypage/UserAccount/ChangePassword.jsx
- src/components/Mypage/UserHistory/UserLike.jsx
- src/components/Mypage/UserHistory/UserWrite.jsx
- src/pages/Community/style.js
- src/pages/MainPage/style.js
- src/pages/MyPage/MyPage.jsx
- src/pages/MyPage/style.js
- src/pages/ServicePage/style.js
1. 푸터 조정 완료 2.마이페이지 반응형 완료 (80%) 3.홈 화면 금주의 팁 이미지 사이즈 조절
> fix. 푸터 조정, 마이페이지 반응형

- src/components/BookMarkList/DetailBookMark.jsx
- src/components/DetailProduct/style.js
- src/components/Mypage/BookmarkPrdtItem.jsx
- src/components/SearchBankList/style.js
- src/components/ServicePage/Bookmarks.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/MyPage/style.js
- src/pages/ServicePage/style.js
1.웹에서 가장 줄였을때 사이즈 조절
2.모바일에서 봤을때 (기준 400px)사이즈 조절
> Feature/feed back fix1.4

- src/components/Community/style.js
- src/components/DetailProduct/style.js
- src/components/SearchBankList/Detail/SearchDepositDetail.jsx
- src/components/SearchBankList/Detail/SearchSavingDetail.jsx
- src/components/SearchBankList/style.js
- src/pages/ServicePage/ServicePage.jsx
- src/pages/ServicePage/style.js
1. 서비스페이지 푸터 수정
2. 갯수 기능 추가
3. 리스트 클릭시 스테이징 범위 기능 수정
> fix. 서비스페이지 푸터 수정

- src/pages/ServicePage/ServicePage.jsx
> feat. 서비스페이지 기능추가 및 UI 수정.

- src/pages/ServicePage/ServicePage.jsx
> fix. 로그삭제.

- src/components/Community/Like.jsx
> Feature/feed back fix1.6v

- src/components/GlobalComponents/Header/Header.jsx
- src/pages/Admin/Admin.jsx
- src/pages/Community/CommunityPage.jsx
- src/pages/LandingPage/LandingPage.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/ServicePage/ServicePage.jsx
- src/pages/SignUpPage/SignUpPage.jsx
- src/routes/index.js
- src/utils/utils.js
feat. 어드민 페이지 접근 권한 설정
fix. 렌더링 오류로 uitl 내 isLoggedIn 변수 -> 함수화
> feat. 어드민 페이지 접근 권한 설정

- src/components/MainPage/BestProducts.jsx
- src/pages/MainPage/style.js
> feat. 금감원 API 및 한국은행 기준금리 최신화

- src/pages/Admin/Admin.jsx
- src/pages/Error/NotFoundPage.jsx
1. 에러페이지 내비개이션 추가 및 ui 수정
2. 어드민페이지 ui 및 문구 수정
> 에러페이지, 어드민페이지 수정
